### ISSUE TITLE
SSLError on Windows

### ISSUE THREAD

**Issue by straight-shoota** [wummel/linkchecker#715]
I get the following error running linkchecker 9.3 GUI on Windows for a https request: `Error: SSLError: hostname 'XXX.net' doesn't match 'YYY.net'`. Seems like it messes up Server Name Indication.
Every browser works fine with the domain in question, as does linkchecker 9.3 CLI on Ubunutu.

**Comment by palsecam** [comment]
Hello @straight-shoota ,
Have you tried to set the SSL verification setting at false ?
Options --> Configuration file --> Edit, and change the line as is
```
# CA cert bundle to use. Set to zero to disable SSL certificate verification.
sslverify=0
```

**Comment by straight-shoota** [comment]
If others find this, this issue is also in the active fork of this repo: linkcheck/linkchecker#66

**Comment by VladimirAlexiev** [comment]
So @straight-shoota why did you close this if sslverify=0 doesn't help? Tracking on https://github.com/wummel/linkchecker/issues/393

**Comment by VladimirAlexiev** [comment]
Actually, setting `sslverify=0` works, so that's an acceptable workaround.

**Comment by straight-shoota** [comment]
@VladimirAlexiev This repository seems to be dead because the maintainer has been inactive for several months. That's why I closed this issue here and opened a new one at linkcheck/linkchecker#66
Btw. in my example the proposed workaround did not work.

**Comment by Emil-nu** [comment]
You may have made the same mistake I did, before I looked deeper in the file ; all settings in the configuration file for Windows desktop version are remarked with #, and it is using default value instead.

Remove the "#" before  sslverify=0 then it will presumable work, it worked for me. 

My problem is because the certificate is created by Let´s Encrypts and it generate a shared certificate, and therefore it find that the certificate is for an other domain than I am testing. 

Shared certificate is very common, and I hope that LinkChecker will make it just as a warning and then proceed instead of stopping.
